# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=16)),
                ('avatar', models.ImageField(upload_to='images')),
                ('address', models.CharField(default='', max_length=64)),
                ('wants_marketing', models.BooleanField(default=True)),
                ('wants_newsletter', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=16)),
                ('badge_logo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=32)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('description', models.TextField()),
                ('base_repro_fee', models.DecimalField(decimal_places=2, max_digits=3)),
                ('max_print_size', models.CharField(default='', max_length=16)),
                ('num_of_orders', models.IntegerField(default=0)),
                ('num_of_views', models.IntegerField(default=0)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_technologies',
            field=models.ManyToManyField(to='products.Technologies'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AddField(
            model_name='artist',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Badge'),
        ),
    ]
