# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=16)),
                ('avatar', models.ImageField(upload_to='images')),
                ('wants_marketing', models.BooleanField(default=True)),
                ('wants_newsletter', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=16)),
                ('badge_logo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='artist',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Badge'),
        ),
    ]
