# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200307_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formats',
            new_name='Format',
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
    ]
