# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200307_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.ManyToManyField(to='products.Room'),
        ),
    ]
