# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200310_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(default='#ilovephotography', max_length=32)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
