# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_hashtag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technologies',
            new_name='Technology',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
    ]
