# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-04 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200330_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_repro_fee',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
        ),
    ]
