# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_auto_20200404_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='assigned_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='size',
            name='longer_side',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
