# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200406_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images', validators=[products.models.image_size_validator]),
        ),
    ]
