# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-19 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200416_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='size',
        ),
    ]
