# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-19 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_format_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='format_description',
            field=models.CharField(default='', max_length=60),
        ),
    ]
