# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-19 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_format_format_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aspect_ratio',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Format'),
        ),
    ]
