# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-19 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='format_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Format'),
        ),
    ]
