# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-19 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200419_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='technology_price_coefficient',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
