# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-24 11:51
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_technology_technology_price_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=16, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator]),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_repro_fee',
            field=models.DecimalField(decimal_places=2, default=4.99, max_digits=6),
        ),
    ]
