# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-24 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200424_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='product',
        ),
    ]
