# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-24 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_hashtag_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hashtag',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
