# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-25 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(default='', max_length=32),
        ),
    ]
