# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-26 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200425_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
