# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-29 18:06
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_num_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=16, validators=[django.contrib.auth.validators.UnicodeUsernameValidator]),
        ),
    ]
